---
- name: Create docker swarm
  docker_swarm:
    state: present
    advertise_addr: "{{swarm_advertise_addr}}"
  register: swarm_info

- name: Publish Swarm Manager Key
  set_fact:
    swarm_manager_join_token: "{{swarm_info.swarm_facts.JoinTokens.Manager}}"
    swarm_worker_join_token: "{{swarm_info.swarm_facts.JoinTokens.Worker}}"
