---
- name: Install apt prerequisites
  include_tasks: "install-docker-{{ansible_distribution}}.yml"

- name: Ensure the docker service is running and enabled
  service:
    name: docker
    enabled: yes
    state: started

- name: Install python docker
  pip:
    name: docker

- name: Configure Swarm
  include: "{{'join' if swarm_join else 'create'}}-{{swarm_role}}.yml"
  when: "swarm_enable"

- name: Configure Solo
  include: "solo.yml"
  when: "not swarm_enable"
