---
- name: Install apt prerequisites
  apt:
    update_cache: yes
    name: [ 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common', 'python3-pip' ]
    state: latest

- name: Install Docker's GPG key
  apt_key:
    id: 0EBFCD88
    url: "https://download.docker.com/linux/ubuntu/gpg"

- name: Add Docker CE apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

- name: Install Docker
  apt:
    update_cache: yes
    name: [ docker-ce, docker-ce-cli, containerd.io ]
    state: latest

- name: Install python docker
  pip:
    name: docker

- name: Configure Swarm
  include: "{{'join' if final_swarm.join else 'create'}}-{{final_swarm.role}}.yml"
  when: "final_swarm.enable"

- name: Configure Solo
  include: "solo.yml"
  when: "not final_swarm.enable"
