---
- name: Install prerequisites and docker
  include_tasks: "install-docker-{{ ansible_distribution }}.yml"

- name: Ensure the docker service is running and enabled
  service:
    name: docker
    enabled: yes
    state: started

- name: Install setuptools
  package:
    name: python3-setuptools

- name: Install python docker
  package:
    name: python3-docker

- name: Configure Swarm
  include_tasks: "{{ 'join' if swarm_join else 'create' }}-{{ swarm_role }}.yml"
  when: "swarm_enable | bool"

- name: Configure Solo
  include_tasks: "solo.yml"
  when: "not swarm_enable"
